PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS accounts (id TEXT PRIMARY KEY, display_name TEXT NOT NULL, cash_cents INTEGER NOT NULL DEFAULT 100000, flex_credits INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS api_keys (id TEXT PRIMARY KEY, account_id TEXT NOT NULL REFERENCES accounts(id), key_hash TEXT NOT NULL UNIQUE, label TEXT NOT NULL, is_admin INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS providers (id TEXT PRIMARY KEY, display_name TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS assets (id TEXT PRIMARY KEY, account_id TEXT NOT NULL REFERENCES accounts(id), provider_id TEXT NOT NULL REFERENCES providers(id), zone TEXT NOT NULL, capacity_kwh REAL NOT NULL, soc_kwh REAL NOT NULL, min_reserve_kwh REAL NOT NULL, charge_kw REAL NOT NULL, discharge_kw REAL NOT NULL);
CREATE TABLE IF NOT EXISTS products (id TEXT PRIMARY KEY, symbol TEXT NOT NULL UNIQUE, zone TEXT NOT NULL, delivery_hour TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'open');
CREATE TABLE IF NOT EXISTS orders (id TEXT PRIMARY KEY, account_id TEXT NOT NULL REFERENCES accounts(id), product_id TEXT NOT NULL REFERENCES products(id), side TEXT NOT NULL CHECK(side IN ('buy','sell')), quantity INTEGER NOT NULL, remaining_qty INTEGER NOT NULL, price_cents INTEGER NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS trades (id TEXT PRIMARY KEY, product_id TEXT NOT NULL REFERENCES products(id), buy_order_id TEXT NOT NULL REFERENCES orders(id), sell_order_id TEXT NOT NULL REFERENCES orders(id), quantity INTEGER NOT NULL, price_cents INTEGER NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS positions (account_id TEXT NOT NULL REFERENCES accounts(id), product_id TEXT NOT NULL REFERENCES products(id), quantity INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(account_id, product_id));
CREATE TABLE IF NOT EXISTS reservations (id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES orders(id), asset_id TEXT NOT NULL REFERENCES assets(id), delivery_hour TEXT NOT NULL, kwh REAL NOT NULL, status TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS idempotency (account_id TEXT NOT NULL REFERENCES accounts(id), key TEXT NOT NULL, request_hash TEXT NOT NULL, response_json TEXT NOT NULL, PRIMARY KEY(account_id, key));
CREATE TABLE IF NOT EXISTS events (id TEXT PRIMARY KEY, entry_type TEXT NOT NULL, account_id TEXT, subject_id TEXT, payload_json TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS anomalies (id TEXT PRIMARY KEY, kind TEXT NOT NULL, subject_id TEXT, detail TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS halts (id TEXT PRIMARY KEY, account_id TEXT, reason TEXT NOT NULL, started_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, ended_at TEXT);
CREATE TABLE IF NOT EXISTS signals (id TEXT PRIMARY KEY, report_id TEXT NOT NULL, zone TEXT NOT NULL, interval_start TEXT NOT NULL, interval_minutes INTEGER NOT NULL, value REAL NOT NULL, unit TEXT NOT NULL, published_at TEXT NOT NULL, fetched_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS settlements (id TEXT PRIMARY KEY, product_id TEXT NOT NULL REFERENCES products(id), price_cents INTEGER NOT NULL, settled_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS settled_positions (id TEXT PRIMARY KEY, settlement_id TEXT NOT NULL REFERENCES settlements(id), account_id TEXT NOT NULL REFERENCES accounts(id), product_id TEXT NOT NULL REFERENCES products(id), quantity INTEGER NOT NULL, pnl_cents INTEGER NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS deposits (id TEXT PRIMARY KEY, account_id TEXT NOT NULL REFERENCES accounts(id), amount_cents INTEGER NOT NULL, reason TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS bots (id TEXT PRIMARY KEY, account_id TEXT NOT NULL REFERENCES accounts(id), bot_index INTEGER NOT NULL UNIQUE, bot_type TEXT NOT NULL, provider_id TEXT NOT NULL, profile_json TEXT NOT NULL, dormant INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS bot_meta (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS router_results (id TEXT PRIMARY KEY, check_id TEXT NOT NULL, family TEXT NOT NULL, subject TEXT NOT NULL, horizon_s INTEGER NOT NULL, probability REAL NOT NULL, band TEXT NOT NULL, baseline INTEGER NOT NULL, jev_probability REAL, created_at TEXT NOT NULL, resolves_at TEXT NOT NULL, outcome INTEGER);
CREATE TABLE IF NOT EXISTS provider_health (provider_id TEXT PRIMARY KEY REFERENCES providers(id), online INTEGER NOT NULL DEFAULT 1, last_heartbeat TEXT, outage_until TEXT);
CREATE TABLE IF NOT EXISTS sandbox_issuance (id TEXT PRIMARY KEY, address_hash TEXT NOT NULL, account_id TEXT NOT NULL REFERENCES accounts(id), issued_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TRIGGER IF NOT EXISTS trades_no_update BEFORE UPDATE ON trades BEGIN SELECT RAISE(ABORT, 'trades are append-only'); END;
CREATE TRIGGER IF NOT EXISTS trades_no_delete BEFORE DELETE ON trades BEGIN SELECT RAISE(ABORT, 'trades are append-only'); END;
CREATE TRIGGER IF NOT EXISTS events_no_update BEFORE UPDATE ON events BEGIN SELECT RAISE(ABORT, 'events are append-only'); END;
CREATE TRIGGER IF NOT EXISTS events_no_delete BEFORE DELETE ON events BEGIN SELECT RAISE(ABORT, 'events are append-only'); END;
CREATE TRIGGER IF NOT EXISTS deposits_no_update BEFORE UPDATE ON deposits BEGIN SELECT RAISE(ABORT, 'deposits are append-only'); END;
CREATE TRIGGER IF NOT EXISTS deposits_no_delete BEFORE DELETE ON deposits BEGIN SELECT RAISE(ABORT, 'deposits are append-only'); END;
CREATE TRIGGER IF NOT EXISTS settled_positions_no_update BEFORE UPDATE ON settled_positions BEGIN SELECT RAISE(ABORT, 'settled_positions are append-only'); END;
CREATE TRIGGER IF NOT EXISTS settled_positions_no_delete BEFORE DELETE ON settled_positions BEGIN SELECT RAISE(ABORT, 'settled_positions are append-only'); END;
