"""Build one specification Markdown file from section sources (DES-GM-SPEC, DEC-SPEC-004).

Input: ``spec.yaml`` (title, document_id, revisions) plus section sources
``NN-*.md`` (``04.1.2-*.md`` for subsections) in numeric order. Output: the
generated front matter (title block, revision history, table of contents, list
of tables, list of figures), the sections without their YAML front matter, and
Appendix A, the generated requirement traceability matrix.

Captions ``Table (Tn): ...`` and ``Figure (Fn): ...`` are numbered in document
order. The output depends only on the inputs, so a rebuild is byte-identical.

Usage: ``python tools/spec_build.py <src dir> <out.md>``.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
from spec_lint import (
    CAPTION,
    HEADING,
    prose_lines,
    section_files,
    split_front_matter,
)

APPENDIX_A = "Appendix A — Requirement Traceability Matrix"


def slug(heading: str, seen: dict[str, int]) -> str:
    """GitHub heading anchor, with -1, -2 suffixes for repeats."""
    base = re.sub(r"[^\w\- ]", "", heading.lower()).replace(" ", "-")
    count = seen.get(base, 0)
    seen[base] = count + 1
    return f"{base}-{count}" if count else base


def cell(text: str) -> str:
    return str(text).replace("|", "\\|").strip()


def build(src_dir: Path, out_path: Path) -> None:
    src_dir, out_path = Path(src_dir), Path(out_path)
    meta = yaml.safe_load((src_dir / "spec.yaml").read_text())
    for key in ("title", "document_id", "revisions"):
        if not meta.get(key):
            raise ValueError(f"spec.yaml: {key} is required")
    revisions = meta["revisions"]

    toc, tables, figures, trace, bodies = [], [], [], {}, []
    seen: dict[str, int] = {}
    for key in (
        "Revision History",
        "Table of Contents",
        "List of Tables",
        "List of Figures",
    ):
        slug(key, seen)
    for path in section_files(src_dir):
        front, body = split_front_matter(path.read_text())
        body_lines, visible = (
            body.strip("\n").splitlines(),
            prose_lines(body.strip("\n")),
        )
        section = ""
        for i, line in enumerate(visible):
            if heading := HEADING.match(line):
                level, section = len(heading[1]), heading[2].strip()
                anchor = slug(section, seen)
                toc.append(f"{'  ' * max(level - 2, 0)}- [{section}](#{anchor})")
            elif caption := CAPTION.match(line):
                kind, cls, text = caption.groups()
                listed = tables if kind == "Table" else figures
                listed.append(f"- {kind} {len(listed) + 1} ({cls}): {text} — {section}")
                body_lines[i] = f"**{kind} {len(listed)} ({cls}): {text}**"
        for requirement in (front or {}).get("requirements") or []:
            trace.setdefault(str(requirement), []).append(section)
        bodies.append("\n".join(body_lines))
    toc.append(f"- [{APPENDIX_A}](#{slug(APPENDIX_A, seen)})")

    out = [
        f"# {meta['title']}",
        "",
        f"**Document ID:** {meta['document_id']}  ",
        f"**Revision:** {revisions[-1]['rev']} ({revisions[-1].get('date', '')})",
        "",
        "> Generated by `tools/spec_build.py` from the section sources; edit those, not this file.",
        "",
        "## Revision History",
        "",
        "| Rev | Date | Author | Summary |",
        "|---|---|---|---|",
        *(
            f"| {cell(r['rev'])} | {cell(r.get('date', ''))} | {cell(r.get('author', ''))} "
            f"| {cell(r.get('summary', ''))} |"
            for r in revisions
        ),
        "",
        "## Table of Contents",
        "",
        *toc,
        "",
        "## List of Tables",
        "",
        *(tables or ["None."]),
        "",
        "## List of Figures",
        "",
        *(figures or ["None."]),
        "",
    ]
    for body in bodies:
        out += [body, ""]
    out += [f"## {APPENDIX_A}", "", "| Requirement | Sections |", "|---|---|"]
    out += [f"| {cell(req)} | {cell(', '.join(trace[req]))} |" for req in sorted(trace)]
    if not trace:
        out.append("| None | — |")
    out_path.write_text("\n".join(out) + "\n")


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print("usage: spec_build.py <src dir> <out.md>", file=sys.stderr)
        return 2
    build(Path(argv[0]), Path(argv[1]))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
